### ISSUE TITLE
Unable to locate package notify-send

### ISSUE THREAD

**Issue by denny611** [nsahq/elgato-key-light-linux#3]
I got below error message, when install dependencies.
    ```E: Unable to locate package notify-send```
And I sovled it by repace packaged name ```notify-send``` with ```libnotify-bin```
    ```sudo apt install libnotify-bin```
Reference: [notify-send-command-not-found](https://www.thegeekdiary.com/notify-send-command-not-found/)

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by jonaswerme** [comment]
Thank you for highlighting the error and providing the solution.

This repo have been neglected for a while, should do a round of updates :)
